# .github/workflows/fmriprep-pr-trigger.yml
name: Run fMRIPrep on Config Change (Self-Hosted)

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      # fires if *any* fmriprep_config.json is added *or* modified
      - 'pipeline/fmri_pipelines/projects/**/fmriprep_config.json'

jobs:
  run-fmriprep:
    # 1️⃣ Gate on PR title
    if: startsWith(github.event.pull_request.title, 'Process')
    runs-on: self-hosted       # make sure your local runner shows “online” in Settings → Actions → Runners

    steps:
      # 2️⃣ Checkout **with full history** so we can diff base↔head
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0       # REQUIRED for git diff on PRs

      # 3️⃣ Find the config that changed
      - name: Locate modified fmriprep_config.json
        id: detect
        run: |
          # diff between PR base SHA and head SHA covers new *and* edited files
          CONFIG_PATH=$(git diff --name-only \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.event.pull_request.head.sha }} \
            -- 'pipeline/fmri_pipelines/projects/**/fmriprep_config.json' | head -n 1)

          if [ -z "$CONFIG_PATH" ]; then
            echo "❌ No config file changed – skipping."
            exit 1
          fi

          echo "✅ Found config: $CONFIG_PATH"
          echo "config_path=$CONFIG_PATH" >> $GITHUB_OUTPUT

      # 4️⃣ Install tiny Python deps (JSON parsing is in stdlib; json5 only if you need comments)
      - run: pip install --upgrade pip

      # 5️⃣ Run fMRIPrep via your helper script
      - name: Run fMRIPrep in Docker
        run: |
          python3 pipeline/fmri_pipelines/run_fmriprep_from_config.py \
            "${{ steps.detect.outputs.config_path }}"
