name: Run fMRIPrep on PR Config Push (Self-Hosted)

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - 'pipeline/fmri_pipelines/projects/**/fmriprep_config.json'

jobs:
  run-fmriprep:
    if: startsWith(github.event.pull_request.title, 'Process')
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find modified config file
        id: detect_config
        run: |
          CONFIG_PATH=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} | grep 'fmriprep_config.json' | head -n 1)
          if [ -z "$CONFIG_PATH" ]; then
            echo "❌ No config file found in this PR."
            exit 1
          fi
          echo "✅ Found config: $CONFIG_PATH"
          echo "config_path=$CONFIG_PATH" >> $GITHUB_OUTPUT

      - name: Install Python deps
        run: pip install --upgrade pip json5

      - name: Run fMRIPrep from config
        run: |
          python pipeline/fmri_pipelines/run_fmriprep_from_config.py "${{ steps.detect_config.outputs.config_path }}"
