name: "[MEG Workstation] Processing data using fMRIPrep | New Config or Config Change"

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - 'pipeline/fmri_pipelines/projects/**/fmriprep_config.json'

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.event.pull_request.title }}" == "[Process]"* ]]; then
            echo "✅ Title is valid."
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "❌ PR title must start with [Process] to run fMRIPrep."
            echo "should_run=false" >> $GITHUB_OUTPUT

  run-fmriprep:
    needs: check-pr-title
    if: ${{ needs.check-pr-title.outputs.should_run == 'true' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Locate modified fmriprep_config.json
        id: detect
        run: |
          CONFIG_PATH=$(git diff --name-only \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.event.pull_request.head.sha }} \
            -- 'pipeline/fmri_pipelines/projects/**/fmriprep_config.json' | head -n 1)

          if [ -z "$CONFIG_PATH" ]; then
            echo "❌ No config file changed – skipping."
            exit 1
          fi

          echo "✅ Found config: $CONFIG_PATH"
          echo "config_path=$CONFIG_PATH" >> $GITHUB_OUTPUT

      - run: pip install --upgrade pip

      - name: Run fMRIPrep in Docker
        run: |
          python3 pipeline/fmri_pipelines/run_fmriprep_from_config.py \
            "${{ steps.detect.outputs.config_path }}"
