name: "[MEG Workstation] Process data check"

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - 'pipeline/fmri_pipelines/projects/**/fmriprep_config.json'

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - id: check
        name: "Verify PR title"
        shell: bash
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          if [[ "$TITLE" == \[Process\]* ]]; then
            echo "✅ Title is valid."
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "No need to run fMRIprep ❌ PR title must start with [Process] to run fMRIPrep."
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  run-fmriprep:
    needs: check-pr-title
    if: ${{ needs.check-pr-title.outputs.should_run == 'true' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Locate modified fmriprep_config.json
        id: detect
        run: |
          CONFIG_PATH=$(git diff --name-only \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.event.pull_request.head.sha }} \
            -- 'pipeline/fmri_pipelines/projects/**/fmriprep_config.json' | head -n 1)
          if [ -z "$CONFIG_PATH" ]; then
            echo "❌ No config file changed – skipping."
            exit 1
          fi
          echo "✅ Found config: $CONFIG_PATH"
          echo "config_path=$CONFIG_PATH" >> $GITHUB_OUTPUT

      - name: Install Python deps
        run: pip install --upgrade pip

      - name: Run fMRIPrep in Docker
        run: |
          python3 pipeline/fmri_pipelines/run_fmriprep_from_config.py \
            "${{ steps.detect.outputs.config_path }}"

      - name: Keep log beside config on runner
        if: always()
        run: |
          cp "$(dirname "${{ steps.detect.outputs.config }}")"/fmriprep_*_*.log \
             /home/hz3752/fmriprep_logs/ 2>/dev/null || true

      # ── copy logs to local stash for later artifact upload ──────────
      - name: Collect logs
        if: always()
        shell: bash
        run: |
          mkdir -p /home/hz3752/fmriprep_logs
          cp "$(dirname "${{ steps.detect.outputs.config }}")"/fmriprep_*_*.log \
             /home/hz3752/fmriprep_logs/ 2>/dev/null || true

      # ── tar derivatives for Box upload (and artifact) ───────────────
      - name: Tar derivatives
        shell: bash
        run: |
          DERIV=/home/hz3752/PycharmProjects/brainimaging-lab-documentation/data-bids/eeg-fmri/${{ steps.detect.outputs.project }}/derivatives/fmriprep
          TAR_NAME=fmriprep_${{ steps.detect.outputs.project }}_${{ github.run_id }}.tar.gz
          tar -czf "$TAR_NAME" -C "$DERIV" .
          echo "tar_name=$TAR_NAME" >> $GITHUB_OUTPUT
        id: tarstep

      # ── upload tarball to Box ───────────────────────────────────────
      - name: Upload derivatives to Box
        uses: benjaminejarrell/box-upload-gh-actions@v1.2
        with:
          box-client-sdk-config: ${{ secrets.BOX_CLIENT_SDK_CONFIG }}
          box-folder-id: 331134301860
          file: ${{ steps.tarstep.outputs.tar_name }}
          destination-filename: ${{ steps.tarstep.outputs.tar_name }}

      # ── attach logs & tarball as GitHub artifacts ───────────────────
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fmriprep-logs
          path: /home/hz3752/fmriprep_logs/*.log

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fmriprep-derivatives
          path: ${{ steps.tarstep.outputs.tar_name }}