name: "[MRI-stimulus computer] MATLAB Eyelink Test"

on:
  workflow_dispatch:     # allow manual runs
  schedule:
    # 2:00 AM Dubai (UTC+4) → 22:00 UTC
    - cron: "0 22 * * *"

jobs:
  test-eyelink:
    runs-on: mri-stimulus-computer
    timeout-minutes: 15

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Verify MATLAB availability
        run: |
          which matlab || echo "MATLAB not found on PATH"
          matlab -batch "disp('MATLAB detected successfully'); exit"

      - name: Install pytest
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest

      - name: Run EyelinkInit pytest
        run: |
          pytest -q tests/test_eyelink_init.py

