name: [MRI-stimulus computer] Self-runner dispatch test

on:
  workflow_dispatch:

jobs:
  run-on-self-hosted:
    runs-on: self-hosted

    steps:
      - name: Print Message
        run: echo "Running on self-hosted by manual trigger"